spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: HikariPool-1
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

# Logging configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom application-specific configuration
lms:
  security:
    admin:
      username: admin
      password: admin123
    user:
      username: user
      password: user123


